sudo: required
language: node_js
services:
  - docker
node_js: stable
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y apache2-utils
  - npm config set frameworks-performance:ab:requests 10
  - npm config set frameworks-performance:ab:concurrent 5
script: npm test
